#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : webencodings
Version  : 0.5
Release  : 1
URL      : https://pypi.python.org/packages/c3/e5/74d05eed73b09752ac3dc4a8a69ae92ffa1ce92fcb03eaa624d1fcd17e33/webencodings-0.5.tar.gz
Source0  : https://pypi.python.org/packages/c3/e5/74d05eed73b09752ac3dc4a8a69ae92ffa1ce92fcb03eaa624d1fcd17e33/webencodings-0.5.tar.gz
Summary  : Character encoding aliases for legacy web content
Group    : Development/Tools
License  : BSD-3-Clause
Requires: webencodings-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
python-webencodings
===================
This is a Python implementation of the `WHATWG Encoding standard
<http://encoding.spec.whatwg.org/>`_.

%package python
Summary: python components for the webencodings package.
Group: Default

%description python
python components for the webencodings package.


%prep
%setup -q -n webencodings-0.5

%build
export LANG=C
export SOURCE_DATE_EPOCH=1487896162
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1487896162
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
