#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : webencodings
Version  : 0.5.1
Release  : 3
URL      : http://pypi.debian.net/webencodings/webencodings-0.5.1.tar.gz
Source0  : http://pypi.debian.net/webencodings/webencodings-0.5.1.tar.gz
Summary  : Character encoding aliases for legacy web content
Group    : Development/Tools
License  : BSD-3-Clause
Requires: webencodings-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
python-webencodings
===================
This is a Python implementation of the `WHATWG Encoding standard
<http://encoding.spec.whatwg.org/>`_.

%package python
Summary: python components for the webencodings package.
Group: Default

%description python
python components for the webencodings package.


%prep
%setup -q -n webencodings-0.5.1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492291776
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1492291776
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
